
application:
  name: DevOpsSimulator
  version: 3.0.0-experimental
  environment: production
  experimental_mode: false

server:
  host: 0.0.0.0
  port: 8080
  ssl_enabled: true
  # Optional: Experimental multi-port setup
  experimental_ports: [9000, 9001, 9002]

logging:
  level: INFO
  format: json
  # Optional experimental logging config
  experimental:
    level: TRACE
    format: structured
    output: /var/log/experimental.log
    ai_analysis: enabled

database:
  host: prod-db.example.com
  port: 5432
  name: devops_prod
  distributed: false
  experimental:
    host: cluster.example.com
    distributed: true
    name: devops_experimental

features:
  auto_scaling: true
  load_balancer: enabled
  backup_enabled: true
  # Advanced/AI-driven features for testing
  experimental:
    auto_scaling: advanced
    load_balancer: ai-optimized
    chaos_engineering: enabled

ai_features:
  enabled: false
  predictive_scaling: true
  anomaly_detection: true
  auto_optimization: true
  model_version: "v2.1.0"

cloud_providers:
  - aws
  - azure
  - gcp
  - digitalocean

security:
  ssl_encryption: true
  zero_trust: enabled
  encryption: AES-256
  audit_logging: comprehensive

# Development configuration (enabled via environment variable)
development:
  enabled: false
  port: 3000
  hot_reload: false
  debug_mode: false
  mock_apis: false
